language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=2.2.12
  - DJANGO_VERSION=3.0.6
  - DJANGO_VERSION=3.1a1

install:
  - "npm install -g npm"
  - "pip install Django==$DJANGO_VERSION"
  - "pip install ."
  - "npm install"
  - "npm install --prefix=tests"
  - "npm run build --prefix=tests"

script: python runtests.py
