language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.11.7

install:
  - "npm install -g npm"
  - "pip install Django==$DJANGO_VERSION"
  - "pip install ."

script: python runtests.py
